openapi: 3.0.1
info:
  title: Emarket
  description: HTTP API
  version: v1
servers:
  - url: /marketing-api
paths:
  /api/v1/campaigns:
    get:
      tags:
        - Campaigns
      operationId: "getCampaignList"
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CampaignDTO'
                nullable: true
    post:
      tags:
        - Campaigns
      operationId: "postCampaign"
      description: "Create a new campaign"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCampaignDTO'
      responses:
        '201':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignDTO'

  /api/v1/campaigns/{id}:
    get:
      tags:
        - Campaigns
      operationId: "getCampaign"
      parameters:
        - name: id
          in: path
          description: "ID of campaign to return"
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignDTO'
components:
  schemas:
    CampaignDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        From:
          type: string
          format: date-time
        to:
          type: string
          format: date-time
        pictureURL:
          type: string
          nullable: true
        detailsUri:
          type: string
          nullable: true
    NewCampaignDTO:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
          example: "Campaign 2022"
        description:
            type: string
            example: "This is a campaign for 2022"
        from:
            type: string
            format: date-time
            example: "2022-01-01T00:00:00Z"
        to:
            type: string
            format: date-time
            example: "2022-12-31T23:59:59Z"
        pictureURL:
            type: string
            example: "https://example"
        detailsUri:
            type: string
            example: "https://example.com/campaigns/1"
